config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
    get 'confirm'
  end
  end

  root "homes#top"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: { maximum: 35 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image   # attachment :image を使ってるならそのままでOK
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :location, presence: true, length: { maximum: 15 }
  validates :text, presence: true, length: { maximum: 195 }
  validates :image, presence: true, if: :published?


  enum status: { published: 0, draft: 1 }
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy 

  has_many :follower, class_name: "Relationship",
                       foreign_key: "follower_id",
                       dependent: :destroy

  has_many :followed, class_name: "Relationship",
                       foreign_key: "followed_id",
                       dependent: :destroy

  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_one_attached :profile_image

  # フォローする
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # フォロー解除
  def unfollow(user_id)
    follower.find_by(followed_id: user_id)&.destroy
  end

  # フォローしているか？
  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  skip_before_action :authenticate_user!, only: [:top]

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    posts_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
  post = Post.find(params[:post_id])
  @comment = current_user.comments.new(comment_params)
  @comment.post_id = post.id

  if @comment.save
    redirect_to post_path(post)
  else
    @post = Post.find(params[:post_id])
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
    render 'posts/show', status: :unprocessable_entity
  end
end


  def destroy
    comment = Comment.find_by(id: params[:id], post_id: params[:post_id])
    comment.destroy if comment
    redirect_to post_path(params[:post_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to post_path(post)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def top
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to post_path(@post.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def confirm
    @posts = current_user.posts.draft.page(params[:page]).reverse_order
  end

  def index
    @posts = Post.published.page(params[:page]).reverse_order
    @posts = @posts.where('location LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.page(params[:page]).per(7).reverse_order
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:location, :text, :image, :status)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.page(params[:page]).per(5).reverse_order
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(8).reverse_order
    @following_users = @user.following_user
    @follower_users  = @user.follower_user
  end

  # 🔽 追加
  def follows
    @user = User.find(params[:id])
    @users = @user.following_user.page(params[:page]).per(5)
  end

  # 🔽 追加
  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user.page(params[:page]).per(5)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="cover align-middle">
  <div class="text-center">
    <p class="sub-title">〜旅行の思い出を共有する〜</p>
    <h1 class="title mb-2">Traveler</h1>

    <%= link_to new_user_registration_path do %>
      <h2 class="btn btn-primary mr-2">新規登録</h2>
    <% end %>

    <%= link_to new_user_session_path do %>
      <h2 class="btn btn-success ml-2">ログイン</h2>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traveler</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <header>
        <div>
          <%= link_to "traveler", root_path, class: "text-white nav-link" %>
        </div>
        <div>
          <%= link_to "トップ", root_path, class: "text-white nav-link" %>
        </div>
        <div>
          <%= link_to "投稿する", new_post_path, class: "text-white nav-link" %>
        </div>
        <div>
          <%= link_to "投稿一覧", posts_path, class: "text-white nav-link" %>
        </div>
        <div><%= link_to "下書き一覧", confirm_posts_path, class: "text-white nav-link" %></div>
        <div>
          <%= link_to "ユーザ一覧", users_path, class: "text-white nav-link" %>
        </div>
        <div>
          <%= link_to "マイページ", user_path(current_user.id), class: "text-white nav-link" %>
        </div>
        <div>
          <%= button_to "ログアウト",
    destroy_user_session_path,
    method: :delete,
    class: "text-white nav-link",
    form: {
      style: "display:inline",
      data: { turbo: false }
    } %>


        </div>
      </header>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_index.html.erb
<div class="row mt-3 mb-3 align-self-end">
  <%= form_with url: posts_path, method: :get, local: true do |f| %>
    <%= f.text_field :search %>
    <%= f.submit '検索する', name: nil %>
  <% end %>
</div>

<div class="row mt-5 index-left w-100">
  <% posts.each do |post| %>
    <div class="one-post col-sm-4 mb-3">
      <%= link_to post_path(post) do %>
        <p class="caption"><%= post.user.name %></p>

        <% if post.image.attached? %>
          <%= image_tag post.image.variant(resize_to_limit: [300, 200]) %><br>
        <% end %>

        <p class="caption"><%= post.location %></p>
        <p class="caption"><%= post.comments.count %> コメント</p>
      <% end %>
    </div>
  <% end %>
</div>

<%= paginate posts %>

app/views/posts/confirm.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">下書き一覧</h1>
    </div>
    <%= render 'index', posts: @posts %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="cover-edit">
  <div class="container">
    <div class="row">
      <h1 class="font-weight-normal mt-5 mb-5">旅行投稿編集</h1>
    </div>

    <% if @post.errors.any? %>
      <div class="card text-center text-white bg-danger mb-3 p-2">
        <%= @post.errors.count %>件のエラーが発生しました
        <%= @post.errors.full_messages.join(' ') %>
      </div>
    <% end %>

    <div class="row">
      <%= form_with model: @post, local: true do |f| %>
        <div class="form-group mb-3">
          <label class="form-label">旅行先</label>
          <%= f.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group mb-3">
          <label class="form-label">感想</label>
          <%= f.text_area :text, rows: 10, class: "form-control" %>
        </div>

        <div class="form-group mb-4">
          <label class="form-label">画像</label><br>
          <% if @post.image.attached? %>
            <%= image_tag @post.image.variant(resize_to_limit: [450, 350]) %><br>
          <% end %>

          <label class="form-label">画像を変更する</label><br>
          <%= f.file_field :image %><br>
        </div>
        <div class="form-group">
        <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: "custom-select w-25 mb-3"} %>
        </div>
        <%= f.submit '保存する', class: "btn btn-success" %><br>
        <%= link_to '投稿詳細ページへ', post_path(@post), class: "btn btn-dark mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="cover-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">旅行投稿一覧</h1>
    </div>

    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-4 mb-3">
          <%= link_to post_path(post) do %>
            <p class="caption"><%= post.user.name %></p>

            <% if post.image.attached? %>
              <%= image_tag post.image.variant(resize_to_limit: [300, 200]) %><br>
            <% end %>

            <p class="caption"><%= post.location %></p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @posts %>

app/views/posts/new.html.erb
<div class="cover-new">
  <div class="cover-overlay">
    <div class="posts-new">
      <h1 class="page-title">旅行新規投稿</h1>

      <% if @post.errors.any? %>
        <div class="card text-center text-white bg-danger mt-3 mb-3 p-2">
          <%= @post.errors.count %>件のエラーが発生しました<br>
          <%= @post.errors.full_messages.join(' / ') %>
        </div>
      <% end %>

      <%= form_with model: @post, local: true, html: { multipart: true } do |f| %>

        <div class="form-group">
          <label>旅行先</label>
          <%= f.text_field :location, class: "form-control" %>
        </div>

        <div class="form-group">
          <label>感想</label>
          <%= f.text_area :text, rows: 10, class: "form-control" %>
        </div>

        <!-- ★ これを追加 -->
        <div class="form-group">
          <label>画像</label>
          <%= f.file_field :image, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.select :status,
              Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"), k] },
              {},
              { class: "custom-select w-25 mb-3" } %>
        </div>

        <%= f.submit "投稿する", class: "btn btn-success" %>

      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="cover-show">
  <div class="container">
    <h1 class="font-weight-normal mt-5 mb-5">旅行投稿詳細</h1>

    <!-- ★ 横並びの親 -->
    <div class="post-and-comments">

      <!-- 左：投稿 -->
      <div class="post-detail">
        <p class="caption"><%= @post.user.name %></p>


        <% if @post.image.attached? %>
          <%= image_tag @post.image.variant(resize_to_limit: [450, 350]) %><br>
        <% end %>

        <p class="caption">
  <%= @post.location %>

  <% if @post.favorited_by?(current_user) %>
    <%= button_to post_favorites_path(@post),
          method: :delete,
          class: "favorite_btn",
          form: { data: { turbo: false } } do %>
      ♥ <%= @post.favorites.count %> いいね
    <% end %>
  <% else %>
    <%= button_to post_favorites_path(@post),
          method: :post,
          class: "favorite_btn",
          form: { data: { turbo: false } } do %>
      ♡ <%= @post.favorites.count %> いいね
    <% end %>
  <% end %>
</p>



        <h2>感想</h2>
        <p id="text"><%= @post.text %></p>

        <% if @post.user == current_user %>
  <%= link_to '編集する', edit_post_path(@post), class: "btn btn-info mr-3" %>
  <%= link_to '削除する', post_path(@post),
        data: { turbo_method: :delete, turbo_confirm: "本当に消しますか？" },
        class: "btn btn-danger" %><br>
<% end %>


        <%= link_to '投稿一覧ページへ', posts_path, class: "btn btn-dark mt-3" %>
      </div>

      <!-- 右：コメント -->
<div class="comments">

  <% if @comment.errors.any? %>
  <div class="card text-center text-white bg-danger mt-3 mb-3 p-2">
    <%= @comment.errors.count %>件のエラーが発生しました
    <%= @comment.errors.full_messages.join(' ') %>
  </div>
<% end %>


  <p>コメント件数：<%= @comments.count %></p>


        <% @comments.each do |comment| %>
          <div class="comments-index mb-2">
            <strong><%= comment.user.name %></strong>
            <%= comment.created_at.strftime('%Y/%m/%d') %><br>

            <div class="d-flex">
              <%= comment.comment %>

              <% if comment.user == current_user %>
                <%= link_to "削除",
                      post_comment_path(@post, comment),
                      data: { turbo_method: :delete },
                      class: "btn btn-sm btn-danger ms-auto" %>
              <% end %>
            </div>
          </div>
        <% end %>

        <%= paginate @comments %>

        <hr>

        <%= form_with(model: [@post, @comment], local: true) do |f| %>
          <%= f.text_area :comment, rows: 3, placeholder: "コメントする" %><br>
          <%= f.submit "送信する", class: "btn btn-success mt-2" %>
        <% end %>
      </div>

    </div>
  </div>
</div>

app/views/users/_index.html.erb
<div class="row mt-5 w-50">
  <% users.each do |user| %>
    <div class="one-post card mt-3">
      <%= link_to user_path(user) do %>
        <div class="d-flex">
          <% if user.profile_image.attached? %>
            <%= image_tag user.profile_image, size: '50x50', class: "mt-3 ml-3 profile-img" %>
          <% else %>
            <%= image_tag "no_image.svg", size: '50x50', class: "mt-3 ml-3 profile-img" %>
          <% end %>
          <p class="caption h4 mt-4"><%= user.name %></p>
        </div>
        <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
      <% end %>
    </div>
  <% end %>
</div>
<%= paginate users %>

app/views/users/edit.html.erb
<div class="cover-user-edit">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">プロフィール編集</h1>
    </div>

    <div class="row mt-5">
      <%= form_with model: @user, local:true do |f| %>
        <div class="form-group">
          <label class="form-label">名前</label>
          <%= f.text_field :name, autofocus: true, placeholder:"名前", class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="form-label">プロフィール画像</label><br>
          <% if @user.profile_image.attached? %>
            <%= image_tag @user.profile_image, size: '100x100', class: "mb-3 profile-img" %><br>
          <% else %>
            <%= image_tag "no_image.svg", size: '100x100', class: "mb-3 profile-img" %><br>
          <% end %>
          <%= f.file_field :profile_image %>
        </div>

        <div class="form-group">
          <label class="form-label">プロフィール</label>
          <%= f.text_field :profile, class: "form-control" %>
        </div>

        <%= f.submit '保存する', class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/followers.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロワー一覧</h1>
    </div>
    <%= render 'index', users: @users %>
  </div>
</div>


    <div class="row mt-5 w-50">
      <% @users.each do |user| %>
        <div class="one-post card mt-3">
          <%= link_to user_path(user) do %>
            <div class="d-flex">
              <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image, size: '50x50', class: "mt-3 ml-3 profile-img" %>
              <% else %>
                <%= image_tag "no_image.svg", size: '50x50', class: "mt-3 ml-3 profile-img" %>
              <% end %>
              <p class="caption h4 mt-4"><%= user.name %></p>
            </div>
            <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= paginate @users %>
  </div>
</div>

app/views/users/follows.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">フォロー一覧</h1>
    </div>
    <%= render 'index', users: @users %>
  </div>
</div>


    <div class="row mt-5 w-50">
      <% @users.each do |user| %>
        <div class="one-post card mt-3">
          <%= link_to user_path(user) do %>
            <div class="d-flex">
              <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image, size: '50x50', class: "mt-3 ml-3 profile-img" %>
              <% else %>
                <%= image_tag "no_image.svg", size: '50x50', class: "mt-3 ml-3 profile-img" %>
              <% end %>
              <p class="caption h4 mt-4"><%= user.name %></p>
            </div>
            <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= paginate @users %>
  </div>
</div>

app/views/users/index.html.erb
<div class="cover-user-index">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <h1 class="font-weight-normal">ユーザ一覧</h1>
    </div>
    <%= render 'index', users: @users %>
  </div>
</div>


    <div class="row mt-5 w-50">
      <% @users.each do |user| %>
        <div class="one-post card mt-3">
          <%= link_to user_path(user) do %>
            <div class="d-flex">
              <% if user.profile_image.attached? %>
                <%= image_tag user.profile_image, size: '50x50', class: "mt-3 profile-img" %>
              <% else %>
                <%= image_tag "no_image.svg", size: '50x50', class: "mt-3 profile-img" %>
              <% end %>
              <p class="caption h4 mt-4"><%= user.name %></p>
            </div>
            <p class="caption"><%= "#{user.posts.count} 投稿" %></p>
          <% end %>
        </div>
      <% end %>
    </div>

    <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
  <div class="container d-flex flex-column align-items-center">
    <div class="row mt-5">
      <% if user_signed_in? && @user == current_user %>
        <h1 class="font-weight-normal">マイページ</h1>
      <% else %>
        <h1 class="font-weight-normal"><%= @user.name %>さんのページ</h1>
      <% end %>
    </div>
    <% if user_signed_in? && @user == current_user %>
      <p class="d-flex align-self-end">
        <%= link_to "プロフィール編集", edit_user_path(@user), class: "btn btn-success" %>
      </p>
    <% end %>
   
    <% if current_user != @user %>
  <% if current_user.following?(@user) %>
    <p class="d-flex align-self-end">
      <%= button_to 'フォロー外す',
    user_relationships_path(@user),
    method: :delete,
    class: "btn btn-danger d-flex align-self-end" %>

    </p>
  <% else %>
    <p class="d-flex align-self-end">
      <%= button_to 'フォローする',
    user_relationships_path(@user),
    method: :post,
    class: "btn btn-success d-flex align-self-end" %>

    </p>
  <% end %>
<% end %>



    <div class="d-flex w-100">
      <% if @user.profile_image.attached? %>
        <%= image_tag @user.profile_image, size: '100x100', class: "mb-3 profile-img" %>
      <% else %>
        <%= image_tag "no_image.svg", size: '100x100', class: "mb-3 profile-img" %>
      <% end %>
      <h4 class="ml-3 mb-3 card w-100 profile"><%= @user.profile %></h4>
    </div>
    <div class="d-flex">
  <%= link_to follows_user_path(@user) do %>
    <h6>フォロー<%= @following_users.count %></h6>
  <% end %>  

  <%= link_to followers_user_path(@user) do %>
    <h6>フォロワー<%= @follower_users.count %></h6>
  <% end %>
</div>
    <div class="row mt-5 index-left w-100">
      <% @posts.each do |post| %>
        <div class="one-post col-sm-3 mb-3">
          <%= link_to post_path(post) do %>
            <% if post.image.attached? %>
             <%= image_tag post.image.variant(resize_to_limit: [200, 133]) %>
            <% end %>
            <p class="caption mb-0"><%= post.location %></p>
            <p class="caption"><%= "#{post.comments.count} コメント" %></p>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= paginate @posts %>
  </div>
</div>